services:
    pgsql:
        image: 'postgres:13'
        ports:
            - '${DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - pgsql:/var/lib/postgresql/data
        networks:
            - app
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
    # app:
    #     build:
    #         context: .
    #         target: development
    #     restart: always
    #     volumes:
    #         - .:/app
    #         - ./node_modules:/app/node_modules
    #     command: sh -c "npm install && npm run start:dev"
    #     ports:
    #         - "${APP_PORT}:3000"
    #     env_file:
    #         - .env
    #     depends_on:
    #         - pgsql
    #     networks:
    #         - app

    n8n:
        image: n8nio/n8n:latest
        container_name: n8n
        ports:
            - "5678:5678"
        environment:
            - GENERIC_TIMEZONE=America/Bogota
            - DB_TYPE=sqlite
            - DB_SQLITE_VACUUM_ON_STARTUP=true
            - N8N_BASIC_AUTH_ACTIVE=true
            - N8N_BASIC_AUTH_USER=admin
            - N8N_BASIC_AUTH_PASSWORD=admin123
            - N8N_HOST=localhost
            - N8N_PORT=5678
            - WEBHOOK_URL=https://5d36-181-62-52-174.ngrok-free.app/
        volumes:
            - ./n8n_data:/home/node/.n8n
        restart: unless-stopped

networks:
    app:
        driver: bridge
volumes:
    pgsql:
        driver: local
